//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.5448
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Buffalo.DBTools {
    using System;
    
    
    /// <summary>
    ///   强类型资源类，用于查找本地化字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Models {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Models() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Buffalo.DBTools.Models", typeof(Models).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   为使用此强类型资源类的所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 using System;
        ///using System.Data;
        ///using System.Configuration;
        ///using Buffalo.DB.BQLCommon;
        ///using Buffalo.DB.BQLCommon.BQLKeyWordCommon;
        ///using Buffalo.DB.BQLCommon.BQLConditionCommon;
        ///using System.Collections.Generic;
        ///using Buffalo.DB.QueryConditions;
        ///using &lt;%=BQLEntityNamespace%&gt;;
        ///using &lt;%=EntityNamespace%&gt;;
        ///using Buffalo.DB.DbCommon;
        ///namespace &lt;%=DataAccessNamespace%&gt;.&lt;%=DataBaseType%&gt;
        ///{
        ///    ///&lt;summary&gt;
        ///    /// &lt;%=Summary%&gt;数据访问层
        ///    ///&lt;/summary&gt;
        ///    public class &lt;%=ClassName%&gt;DataAccess :BQ [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string BQLDataAccess {
            get {
                return ResourceManager.GetString("BQLDataAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 using System;
        ///using System.Data;
        ///using System.Configuration;
        ///using Buffalo.DB.EntityInfos;
        ///using Buffalo.DB.BQLCommon;
        ///using Buffalo.DB.BQLCommon.BQLConditionCommon;
        ///using Buffalo.DB.PropertyAttributes;
        ///namespace &lt;%=BQLEntityNamespace%&gt;
        ///{
        ///    [DataBaseAttribute(&quot;&lt;%=DBName%&gt;&quot;)]
        ///    public partial class &lt;%=DBName%&gt; :BQLDataBaseHandle&lt;&lt;%=DBName%&gt;&gt; 
        ///    {
        ///    }
        ///    
        ///}
        /// 的本地化字符串。
        /// </summary>
        internal static string BQLDB {
            get {
                return ResourceManager.GetString("BQLDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 using System;
        ///using System.Data;
        ///using System.Configuration;
        ///using Buffalo.DB.EntityInfos;
        ///using Buffalo.DB.BQLCommon;
        ///using Buffalo.DB.BQLCommon.BQLConditionCommon;
        ///using Buffalo.DB.PropertyAttributes;
        ///namespace &lt;%=BQLEntityNamespace%&gt;
        ///{
        ///    public partial class &lt;%=DBName%&gt;
        ///    {
        ///        private static &lt;%=DBName%&gt;_&lt;%=ClassName%&gt; _&lt;%=ClassName%&gt; = AddToDB(new &lt;%=DBName%&gt;_&lt;%=ClassName%&gt;()) as &lt;%=DBName%&gt;_&lt;%=ClassName%&gt;;
        ///    
        ///        public static &lt;%=DBName%&gt;_&lt;%=ClassName%&gt; &lt;%=ClassName%&gt;
        ///       [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string BQLEntity {
            get {
                return ResourceManager.GetString("BQLEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 using System;
        ///using &lt;%=EntityNamespace%&gt;;
        ///using System.Collections.Generic;
        ///using Buffalo.DB.DataBaseAdapter;
        ///using Buffalo.DB.CommBase.BusinessBases;
        ///using Buffalo.DB.CommBase.DataAccessBases;
        ///using Buffalo.DB.DbCommon;
        ///using Buffalo.DB.QueryConditions;
        ///using Buffalo.DB.CommBase;
        ///namespace &lt;%=BusinessNamespace%&gt;
        ///{
        ///    /// &lt;summary&gt;
        ///    ///  &lt;%=Summary%&gt;业务层
        ///    /// &lt;/summary&gt;
        ///    public class &lt;%=BusinessClassName%&gt;: &lt;%=BaseBusinessClass%&gt;
        ///    {
        ///        public &lt;%=ClassName%&gt;Business()
        ///       [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Business {
            get {
                return ResourceManager.GetString("Business", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 using System;
        ///using System.Data;
        ///using Buffalo.DB.CommBase.DataAccessBases;
        ///using Buffalo.DB.DbCommon;
        ///using &lt;%=EntityNamespace%&gt;;
        ///using System.Collections.Generic;
        ///using &lt;%=DataAccessNamespace%&gt;.IDataAccess;
        ///
        ///namespace &lt;%=DataAccessNamespace%&gt;.&lt;%=DataBaseType%&gt;
        ///{
        ///    ///&lt;summary&gt;
        ///    /// &lt;%=Summary%&gt;数据访问层
        ///    ///&lt;/summary&gt;
        ///    public class &lt;%=ClassName%&gt;DataAccess : DataAccessModel&lt;&lt;%=ClassName%&gt;&gt;,I&lt;%=ClassName%&gt;DataAccess
        ///    {
        ///        public &lt;%=ClassName%&gt;DataAccess(DataBaseOperate oper):  [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string DataAccess {
            get {
                return ResourceManager.GetString("DataAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 using System;
        ///using System.Collections.Generic;
        ///using System.Text;
        ///using System.Data;
        ///using Buffalo.DB.CommBase;
        ///using Buffalo.Kernel.Defaults;
        ///using Buffalo.DB.PropertyAttributes;
        ///namespace &lt;%=EntityNamespace%&gt;;
        ///{
        ///	/// &lt;summary&gt;
        ///    /// &lt;%=Summary%&gt;
        ///    /// &lt;/summary&gt;
        ///    public partial class &lt;%=ClassName%&gt;: &lt;%=EntityBaseType%&gt;
        ///    {
        ///&lt;%=Params%&gt;
        ///        
        ///&lt;%=Relations%&gt;
        ///    }
        ///}
        /// 的本地化字符串。
        /// </summary>
        internal static string Entity {
            get {
                return ResourceManager.GetString("Entity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 using System;
        ///using System.Collections.Generic;
        ///using System.Text;
        ///using &lt;%=EntityNamespace%&gt;;
        ///using Buffalo.DB.CommBase.DataAccessBases;
        ///namespace &lt;%=DataAccessNamespace%&gt;.IDataAccess
        ///{
        ///	///&lt;summary&gt;
        ///    /// &lt;%=Summary%&gt;数据访问层接口
        ///    ///&lt;/summary&gt;
        ///    public interface I&lt;%=ClassName%&gt;DataAccess : IDataAccessModel&lt;&lt;%=ClassName%&gt;&gt;
        ///    {
        ///		
        ///    }
        ///}
        ///
        ///
        ///
        /// 的本地化字符串。
        /// </summary>
        internal static string IDataAccess {
            get {
                return ResourceManager.GetString("IDataAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 using System;
        ///using System.Data;
        ///using System.Collections.Generic;
        ///using Buffalo.DB.CommBase;
        ///using Buffalo.Kernel.Defaults;
        ///using Buffalo.DB.PropertyAttributes;
        ///namespace &lt;%=EntityNamespace%&gt;
        ///{
        ///	
        ///	/// &lt;summary&gt;
        ///	///  &lt;%=Summary%&gt;
        ///	/// &lt;/summary&gt;
        ///	public partial class &lt;%=ClassFullName%&gt;
        ///	{
        ///		
        ///	}
        ///}
        /// 的本地化字符串。
        /// </summary>
        internal static string UserEntity {
            get {
                return ResourceManager.GetString("UserEntity", resourceCulture);
            }
        }
    }
}
